package BLL;
// Generated 18-dec-2014 15:37:03 by Hibernate Tools 4.3.1



/**
 * Verzameling generated by hbm2java
 */
public class Verzameling  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String beschrijving;
     private boolean inBezit;
     private int categoryId;
     private int typeId;

    public Verzameling() {
    }

    public Verzameling(String naam, String beschrijving, boolean inBezit, int categoryId, int typeId) {
       this.naam = naam;
       this.beschrijving = beschrijving;
       this.inBezit = inBezit;
       this.categoryId = categoryId;
       this.typeId = typeId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getBeschrijving() {
        return this.beschrijving;
    }
    
    public void setBeschrijving(String beschrijving) {
        this.beschrijving = beschrijving;
    }
    public boolean isInBezit() {
        return this.inBezit;
    }
    
    public void setInBezit(boolean inBezit) {
        this.inBezit = inBezit;
    }
    
        public boolean getInBezit() {
        return this.inBezit;
    }
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId + 1;
    }
    public int getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(int typeId) {
        this.typeId = typeId + 1;
    }

    @Override
    public String toString()
    {
        return naam;
    }

}


